language: python

cache: pip

python:
  - "2.7"
  - "3.4"
    
install:
    - pip install -r requirements.txt    # installs dependencies listed in requirements.txt
    - pip install . --upgrade		 # installs radvel from current git branch
    - python setup.py build_ext -i       # build C extension

# run tests in Travis-CI virtual env
script:
    - test_api

    
